import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import IntlPolyfills from '../components/IntlPolyfills'
import {NextIntlClientProvider} from 'next-intl'
import {notFound} from 'next/navigation'
import {ReactNode} from "react";


const inter = Inter({ subsets: ['latin'] })

type Props = {
  children: ReactNode;
  params: {locale: string};
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'es'}];
}

export default async function LocaleLayout({
    children,
    params: {locale}
  }: Props) {  let messages

  try {
    messages = (await import(`../../messages/${locale}.json` as string)).default;
  } catch (error) {
    notFound()
  }

  return (
      <html lang={locale}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <IntlPolyfills/>
          <body className={inter.className}>
              {children}
          </body>
        </NextIntlClientProvider>
    </html>
  )
}
